<a href="https://colab.research.google.com/github/Suraram-Spandana/MDS_LABORATORY/blob/main/MDS_WEEK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import random

print("--- Demonstrating Random Functions with an Array (List) ---")

# Our main array (Python list) of elements
my_elements = ['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape', 'honeydew']
print(f"\nOriginal list of elements: {my_elements}")

# 1. Seeding for reproducibility
random.seed(42)
print("\n1. Seeding (seed=42):")
print(f"  Random float after seed: {random.random()}")
print(f"  Random integer (1-10) after seed: {random.randint(1, 10)}")

# 2. random() - Generate a random float between 0.0 and 1.0
print("\n2. random() - Random float (no seed influence now):")
print(f"  {random.random()}")

# 3. randint(a, b) - Generate a random integer between a and b (inclusive)
print("\n3. randint(1, 10) - Random integer between 1 and 10:")
print(f"  {random.randint(1, 10)}")

# 4. choice(sequence) - Pick a random element from our list
print("\n4. choice() - Random element from 'my_elements':")
print(f"  Chosen element: {random.choice(my_elements)}")

# 5. shuffle(list) - Randomly reorder items in our list (in-place)
print("\n5. shuffle() - Shuffling 'my_elements':")
original_my_elements = list(my_elements) # Create a copy to show original
random.shuffle(my_elements)
print(f"  Original list (before shuffle): {original_my_elements}")
print(f"  Shuffled list: {my_elements}")

# 6. uniform(a, b) - Generate a random float between a and b (inclusive)
print("\n6. uniform(10.0, 20.0) - Random float between 10.0 and 20.0:")
print(f"  {random.uniform(10.0, 20.0)}")

# 7. randrange(start, stop, step) - Generate a random integer
print("\n7. randrange(0, 100, 10) - Random multiple of 10 between 0 and 90:")
print(f"  {random.randrange(0, 100, 10)}")

# 8. sample(population, k) - Choose k unique random elements from our list
print("\n8. sample('my_elements', k=3) - 3 unique random elements:")
print(f"  Sampled elements: {random.sample(my_elements, k=3)}")

# 9. choices(population, weights=None, k=1) - Choose k random elements with replacement (with weights)
# Using a subset of my_elements for a weighted example
weighted_choices_elements = ['apple', 'banana', 'cherry']
weights = [0.6, 0.3, 0.1]
print("\n9. choices() - Weighted random choices (5 times) from a subset:")
print(f"  List: {weighted_choices_elements}, Weights: {weights}")
print(f"  Chosen: {random.choices(weighted_choices_elements, weights=weights, k=5)}")

--- Demonstrating Random Functions ---

1. Seeding (seed=123):
  First random float after seed: 0.052363598850944326
  First random integer (1-10) after seed: 2
  Re-seeding (seed=123):
  Second random float after re-seed: 0.052363598850944326
  Second random integer (1-10) after re-seed: 2

2. random() - Random float:
  0.7689563885870707

3. randint(1, 10) - Random integer between 1 and 10:
  5

4. choice() - Random element from list:
  List: ['red', 'green', 'blue', 'yellow', 'purple']
  Chosen element: red

5. shuffle() - Shuffling a list:
  Original list: ['red', 'green', 'blue', 'yellow', 'purple']
  Shuffled list: ['purple', 'green', 'blue', 'yellow', 'red']

6. uniform(10.0, 20.0) - Random float between 10.0 and 20.0:
  13.407982278770701

7. randrange(0, 100, 10) - Random multiple of 10 between 0 and 90:
  0

8. sample(population, k=5) - 5 unique random numbers from 1-49:
  [11, 9, 22, 36, 45]

9. choices() - Weighted random choices (3 times):
  List: ['gold', 'silver', 'bronz

In [2]:
import numpy as np

print("--- NumPy Array Manipulation ---")

# 1. Creating a sample array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\nOriginal Array (3x4):")
print(arr)

# --- Indexing ---
print("\n--- Indexing ---")
# Accessing a single element (row, column)
print(f"Element at (0, 1): {arr[0, 1]} (should be 2)")
# Accessing a row
print(f"First row: {arr[0]}")
# Accessing a column
print(f"Second column: {arr[:, 1]}")

# --- Slicing ---
print("\n--- Slicing ---")
# Slice rows and columns (start:end, start:end)
print("Slice (rows 0-1, cols 1-3):")
print(arr[0:2, 1:4])
# Slice all rows, specific columns
print("All rows, last two columns:")
print(arr[:, -2:])
# Slice specific row, all columns
print("Second row, all columns:")
print(arr[1, :])

# --- Reshaping ---
print("\n--- Reshaping ---")
# Reshape to a 2x6 array
arr_reshaped = arr.reshape(2, 6)
print("Reshaped to 2x6:")
print(arr_reshaped)
# Flatten the array to 1D
arr_flattened = arr.flatten()
print("Flattened to 1D:")
print(arr_flattened)

# --- Joining ---
print("\n--- Joining ---")
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(f"Array 1:\n{arr1}")
print(f"Array 2:\n{arr2}")

# Concatenate along rows (axis=0)
arr_joined_rows = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along rows (axis=0):")
print(arr_joined_rows)

# Concatenate along columns (axis=1)
arr_joined_cols = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along columns (axis=1):")
print(arr_joined_cols)

# Using vstack (vertical stack, equivalent to concatenate axis=0)
arr_vstack = np.vstack((arr1, arr2))
print("Vstack (vertical stack):")
print(arr_vstack)

# Using hstack (horizontal stack, equivalent to concatenate axis=1)
arr_hstack = np.hstack((arr1, arr2))
print("Hstack (horizontal stack):")
print(arr_hstack)

# --- Splitting ---
print("\n--- Splitting ---")
long_arr = np.arange(16).reshape(4, 4)
print(f"Original array for splitting (4x4):\n{long_arr}")

# Split into 2 equal parts vertically (along rows, axis=0)
arr_split_v = np.vsplit(long_arr, 2)
print("Split into 2 equal parts vertically:")
print(f"Part 1:\n{arr_split_v[0]}")
print(f"Part 2:\n{arr_split_v[1]}")

# Split into 2 equal parts horizontally (along columns, axis=1)
arr_split_h = np.hsplit(long_arr, 2)
print("Split into 2 equal parts horizontally:")
print(f"Part 1:\n{arr_split_h[0]}")
print(f"Part 2:\n{arr_split_h[1]}")

# Split into custom sections using np.split()
# Split `long_arr` after the 1st and 3rd rows (axis=0)
arr_split_custom_rows = np.split(long_arr, [1, 3], axis=0)
print("Split after 1st and 3rd rows (axis=0):")
for i, part in enumerate(arr_split_custom_rows):
    print(f"Part {i+1}:\n{part}")

# Split `long_arr` after the 1st and 3rd columns (axis=1)
arr_split_custom_cols = np.split(long_arr, [1, 3], axis=1)
print("Split after 1st and 3rd columns (axis=1):")
for i, part in enumerate(arr_split_custom_cols):
    print(f"Part {i+1}:\n{part}")

--- NumPy Array Manipulation ---

Original Array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

--- Indexing ---
Element at (0, 1): 2 (should be 2)
First row: [1 2 3 4]
Second column: [ 2  6 10]

--- Slicing ---
Slice (rows 0-1, cols 1-3):
[[2 3 4]
 [6 7 8]]
All rows, last two columns:
[[ 3  4]
 [ 7  8]
 [11 12]]
Second row, all columns:
[5 6 7 8]

--- Reshaping ---
Reshaped to 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Flattened to 1D:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

--- Joining ---
Array 1:
[[1 2]
 [3 4]]
Array 2:
[[5 6]
 [7 8]]
Concatenated along rows (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along columns (axis=1):
[[1 2 5 6]
 [3 4 7 8]]
Vstack (vertical stack):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Hstack (horizontal stack):
[[1 2 5 6]
 [3 4 7 8]]

--- Splitting ---
Original array for splitting (4x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Split into 2 equal parts vertically:
Part 1:
[[0 1 2 3]
 [4 5 6 7]]
Part 2:
[[ 8  9 10 11]
 [12 13 14

In [ ]:
import numpy as np

print("--- Computation on NumPy Arrays ---")

# --- Universal Functions (Ufuncs) for element-wise operations ---
print("\n--- Universal Functions (Ufuncs) ---")
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")

# Element-wise addition
print(f"Addition (arr1 + arr2): {arr1 + arr2}")
# Element-wise subtraction
print(f"Subtraction (arr1 - arr2): {arr1 - arr2}")
# Element-wise multiplication
print(f"Multiplication (arr1 * arr2): {arr1 * arr2}")
# Element-wise division
print(f"Division (arr1 / arr2): {arr1 / arr2}")

# Exponentiation
print(f"Exponentiation (arr1 ** 2): {arr1 ** 2}")

# Trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
print(f"Angles (radians): {angles}")
print(f"Sine of angles: {np.sin(angles)}")
print(f"Cosine of angles: {np.cos(angles)}")

# Exponential and Logarithmic functions
exp_arr = np.array([0, 1, 2, 3])
print(f"Exp Array: {exp_arr}")
print(f"e^x: {np.exp(exp_arr)}")
print(f"ln(x+1) for exp_arr: {np.log1p(exp_arr)}") # log(1+x)

# --- Aggregation Functions (Mathematical Methods) ---
print("\n--- Aggregation Functions ---")
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix:\n{matrix}")

# Sum of all elements
print(f"Sum of all elements: {np.sum(matrix)}")
print(f"Sum of rows (axis=0): {np.sum(matrix, axis=0)}") # Summing down columns
print(f"Sum of columns (axis=1): {np.sum(matrix, axis=1)}") # Summing across rows

# Minimum and Maximum
print(f"Minimum element: {np.min(matrix)}")
print(f"Maximum element: {np.max(matrix)}")

# Mean and Standard Deviation
print(f"Mean of all elements: {np.mean(matrix)}")
print(f"Standard Deviation of all elements: {np.std(matrix)}")

# Product of all elements
print(f"Product of all elements: {np.prod(matrix)}")

# --- Broadcasting ---
print("\n--- Broadcasting ---")
arr_b = np.array([1, 2, 3])
scalar_b = 10
print(f"Array for broadcasting: {arr_b}")
print(f"Scalar for broadcasting: {scalar_b}")
print(f"Array + Scalar: {arr_b + scalar_b}")

matrix_b = np.arange(9).reshape(3, 3)
vector_b = np.array([1, 0, -1])
print(f"Matrix for broadcasting:\n{matrix_b}")
print(f"Vector for broadcasting: {vector_b}")
print(f"Matrix + Vector (row-wise addition):\n{matrix_b + vector_b}")

In [57]:
import random
arr=[1,2,3,4,5,6,7,8,9,10]
a=['a','b','c','d','e','f','g','h','i','j','k']
random.shuffle(arr)

# random.seed(10)
print(arr)
print(f"  Chosen element: {random.choice(arr)}")
print(f"  {random.randint(1, 100)}")
print(f"  {random.randrange(0, 100, 10)}")
print(f"  Sampled elements: {random.sample(arr, k=3)}")
print(f"  Chosen: {random.choices(arr,k=5)}")

[6, 5, 10, 4, 8, 3, 7, 2, 9, 1]
  Chosen element: 1
  52
  30
  Sampled elements: [3, 10, 5]
  Chosen: [3, 8, 1, 7, 4]


In [59]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\nOriginal Array (3x4):")
print(arr)

print(f"Element at (0, 1): {arr[0, 1]} (should be 2)")
print(f"Second column: {arr[:, 1]}")
arr_flattened = arr.flatten()
print(arr_flattened)




Original Array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at (0, 1): 2 (should be 2)
Second column: [ 2  6 10]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
