<a href="https://colab.research.google.com/github/Suraram-Spandana/MDS_LABORATORY/blob/main/MDS_WEEK_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [1]:
#installing numpy
pip install numpy


In [3]:
#remaning the numpy as np and checking version
import numpy as np
print(np.__version__)

2.0.2


In [4]:
#defines the diffeeence between the numpy and list interms of memory and time
import time
import numpy as np

# Define a large size for comparison
size = 10**6

# --- Python List ---
print(f"Comparing Python list vs. NumPy array for {size} elements:")

# Create a Python list
start_time = time.time()
python_list = list(range(size))
end_time = time.time()
print(f"Python List creation time: {end_time - start_time:.6f} seconds")

# Perform an operation (e.g., element-wise addition)
start_time = time.time()
python_list_result = [x + 1 for x in python_list]
end_time = time.time()
print(f"Python List element-wise addition time: {end_time - start_time:.6f} seconds")

# --- NumPy Array ---

# Create a NumPy array
start_time = time.time()
numpy_array = np.arange(size)
end_time = time.time()
print(f"NumPy Array creation time: {end_time - start_time:.6f} seconds")

# Perform an operation (e.g., element-wise addition)
start_time = time.time()
numpy_array_result = numpy_array + 1
end_time = time.time()
print(f"NumPy Array element-wise addition time: {end_time - start_time:.6f} seconds")


Comparing Python list vs. NumPy array for 1000000 elements:
Python List creation time: 0.025887 seconds
Python List element-wise addition time: 0.047515 seconds
NumPy Array creation time: 0.003078 seconds
NumPy Array element-wise addition time: 0.003057 seconds


In [5]:
import sys

# --- Memory Comparison ---
print(f"\nComparing memory usage for {size} elements:")

# Memory usage of Python list
# sys.getsizeof() only reports the size of the list object itself, not the elements it contains.
# To get a more accurate total, we sum the size of the list object and each element.
python_list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(item) for item in python_list)
print(f"Python List memory usage: {python_list_memory / (1024*1024):.4f} MB")

# Memory usage of NumPy array
# .nbytes gives the total bytes consumed by the array elements.
numpy_array_memory = numpy_array.nbytes
print(f"NumPy Array memory usage: {numpy_array_memory / (1024*1024):.4f} MB")

print("\nSummary: NumPy arrays are generally more memory-efficient and significantly faster for numerical operations on large datasets compared to Python lists.")


Comparing memory usage for 1000000 elements:
Python List memory usage: 34.3323 MB
NumPy Array memory usage: 7.6294 MB

Summary: NumPy arrays are generally more memory-efficient and significantly faster for numerical operations on large datasets compared to Python lists.


list

In [92]:
#creating list
my_list=[17,1,2,3,4,5]

In [93]:
#checking the type of list
type(my_list)


list

numpy

In [94]:
#converting the list into array using numpy np
arr1=np.array(my_list)

In [95]:
print(arr1)

[17  1  2  3  4  5]


In [99]:
#checking the type of array
type(arr1)

numpy.ndarray

In [100]:
#checking the the type of dimention for the array
arr1.ndim

1

In [15]:
#checking the data type of the array
arr1.dtype

dtype('int64')

In [102]:
#checking the data type name of the array
arr1.dtype.name

'int64'

In [103]:
#checking the size of the array
arr1.size

6

In [20]:
#checking the shape of the array
arr1.shape

(5,)

In [21]:
#checking the no. of bytes occupied by the array
arr1.nbytes

40

tuple

In [106]:
#creating tuple
my_tuple=(17,2,3,4,5)
#checking the type of tuple
type(my_tuple)

tuple

tuple1=(1,)----tuple
tuple2=(1)-----list

In [107]:
#creating tuple with single  element
tuple2=(17,)

In [27]:
type(tuple2)

int

In [31]:
#conerting tuple into array using numpy as np
arr2=np.array(my_tuple)

In [109]:
# Create a Python list of lists to represent a 2D array
python_2d_list = [
    [17, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Python 2D List:")
print(python_2d_list)

Python 2D List:
[[17, 2, 3], [4, 5, 6], [7, 8, 9]]


In [110]:
import numpy as np

# Convert the Python list of lists to a NumPy 2D array
numpy_2d_array = np.array(python_2d_list)

print("\nNumPy 2D Array:")
print(numpy_2d_array)
print("Shape of NumPy 2D Array:", numpy_2d_array.shape)
print("Dimensions of NumPy 2D Array:", numpy_2d_array.ndim)


NumPy 2D Array:
[[17  2  3]
 [ 4  5  6]
 [ 7  8  9]]
Shape of NumPy 2D Array: (3, 3)
Dimensions of NumPy 2D Array: 2


In [113]:
#creating the 2d matrix using list
list_1=[[17,2],[3,4]]
print(list_1)

[[17, 2], [3, 4]]


In [112]:
#converting 2d matrix into 2d array
matrix=np.array(list_1)
print(matrix)

[[17  2]
 [ 3  4]]


In [37]:
#checking the dimention of the array
matrix.ndim

2

In [38]:
#checking the shape of the array
matrix.shape

(2, 2)

In [114]:
#converting 2d array into 1d array using flatten()
matrix.flatten()
matrix.shape
matrix.ndim

array([17,  2,  3,  4])

In [117]:
#converting 2d array into 1d array using ravel()
matrix.ravel()
matrix.ndim

array([17,  2,  3,  4])

In [119]:
#creating the 2d array using numpy
arr5=np.array([[17,2],[3,4]])
print(arr5)

[[17  2]
 [ 3  4]]


In [54]:
#creating the 2d array using matrix function in numpy
arr6=np.matrix([[1,2],[3,4]])
print(arr6)

[[1 2]
 [3 4]]


In [55]:
import numpy as np

# Create a 1D array with numbers from 1 to 100 (exclusive of 101)
arr_1_to_100 = np.arange(1, 101)

print(arr_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [56]:
# Create a 1D array with numbers from 1 to 100 (exclusive of 100)
arr6=np.arange(1,100)
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [61]:
# Create a 1D array with even numbers from 1 to 100
arr6=np.arange(0,100,2)
print(arr6)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [121]:
# Create a 1D array with numbers divisible by 17 from 1 to 100
arr6=np.arange(0,100,17)
print(arr6)

[ 0 17 34 51 68 85]


In [66]:
#creating 2d array from 0-9 using reshape()
matrix2=np.arange(0,10).reshape(2,5)
print(matrix2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
import numpy as np

# Generate numbers up to (but not including) 100, starting implicitly from 0
# Then, use slicing [::2] to get every second number, which will be the even numbers.
even_numbers = np.arange(100)[::2]

print(even_numbers)

np.zeros and np.ones

In [125]:
#creating 3 by 3 matrix with zeros
a=np.zeros((3,3))
a.dtype
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [126]:
#creating 3 by 3 matrix with zeros with data type int
a=np.zeros((3,3),dtype='int')
a=np.zeros((3,3))
a.dtype
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [127]:
#creating 3 by 3 matrix with ones with data type int
a=np.ones((3,3),dtype='int')
a.dtype

dtype('int64')

np.full()

In [130]:
#creating 3 by 3 matrix with a single number
c=np.full((3,3),17)
print(c)

[[17 17 17]
 [17 17 17]
 [17 17 17]]


In [129]:
#creating 3 by 3 identity matrix
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [133]:
#creating and array of evenly spaced numbers over a specified interval.
f=np.linspace(0,1,17)
print(f)

[0.     0.0625 0.125  0.1875 0.25   0.3125 0.375  0.4375 0.5    0.5625
 0.625  0.6875 0.75   0.8125 0.875  0.9375 1.    ]


In [ ]:
# Demonstrate np.linspace()
# Generate 7 evenly spaced numbers between 5 and 15 (inclusive)
linear_space_array = np.linspace(5, 15, 7)
print('Generated array with linspace:')
print(linear_space_array)

# Generate 5 evenly spaced numbers between 0 and 1, excluding the endpoint
linear_space_no_endpoint = np.linspace(0, 1, 5, endpoint=False)
print('\nGenerated array without endpoint:')
print(linear_space_no_endpoint)

In [84]:
#generating random numbers ina an array using random()
g=np.random.random((3,3))
print(g)

[[0.37238272 0.37747776 0.43192531]
 [0.81680341 0.79749142 0.61389854]
 [0.70115532 0.97086223 0.35903921]]


In [134]:
#generate a NumPy array with evenly spaced values within a given interval
arr1=np.arange(17,25)
print(arr1)

[17 18 19 20 21 22 23 24]


In [ ]:
# Demonstrate np.arange()
# Generate numbers from 0 to 9 (default start=0, step=1)
array_default = np.arange(10)
print('Array with default start and step:')
print(array_default)

# Generate numbers from 5 to 15 with a step of 3
array_custom_step = np.arange(5, 16, 3)
print('\nArray with custom start, stop, and step:')
print(array_custom_step)

# Generate floating-point numbers
array_float = np.arange(0.5, 2.5, 0.5)
print('\nArray with floating-point values:')
print(array_float)

In [135]:
#changing the element in an array
arr1[0]=111
print(arr1)

[111  18  19  20  21  22  23  24]


In [ ]:
#finding the max element in an array
arr1.max()

In [136]:
#finding the min element in an array
arr1.min()

np.int64(18)

### Converting Strings to NumPy Arrays

When converting a list or tuple of strings to a NumPy array, NumPy will infer the data type as a string type (e.g., `<U5` for Unicode strings with a maximum length of 5). If the strings represent numbers, you can explicitly convert them to a numeric `dtype`.

In [137]:
# Convert a list of strings to a NumPy array
string_list = ['apple', 'banana', 'cherry']
string_array = np.array(string_list)
print(f"Array from strings: {string_array}")
print(f"Data type: {string_array.dtype}")

# Convert a list of numeric strings to a NumPy array with numeric dtype
numeric_string_list = ['10', '20', '30']
numeric_string_array = np.array(numeric_string_list, dtype=int)
print(f"\nArray from numeric strings (as int): {numeric_string_array}")
print(f"Data type: {numeric_string_array.dtype}")

# Handle strings of different lengths
mixed_length_strings = ['cat', 'dog', 'elephant']
mixed_array = np.array(mixed_length_strings)
print(f"\nArray with mixed length strings: {mixed_array}")
print(f"Data type: {mixed_array.dtype}")

Array from strings: ['apple' 'banana' 'cherry']
Data type: <U6

Array from numeric strings (as int): [10 20 30]
Data type: int64

Array with mixed length strings: ['cat' 'dog' 'elephant']
Data type: <U8


In [139]:
# Convert a single dictionary to a NumPy array (results in an array containing the dictionary object)
dict_single = {'name': 'Alice', 'age': 30}
dict_array_single = np.array(dict_single)
print(f"Array from single dictionary: {dict_array_single}")
print(f"Data type: {dict_array_single.dtype}")

# Convert a list of dictionaries to a NumPy array
dict_list = [
    {'name': 'Bob', 'age': 25},
    {'name': 'Charlie', 'age': 35}
]
dict_array_list = np.array(dict_list)
print(f"\nArray from list of dictionaries: {dict_array_list}")
print(f"Data type: {dict_array_list.dtype}")

# Extract specific values (e.g., 'age') from a list of dictionaries into a numeric NumPy array
ages = np.array([d['age'] for d in dict_list])
print(f"\nExtracted ages into array: {ages}")
print(f"Data type: {ages.dtype}")

# Extract keys into an array
keys = np.array(dict_single.keys())
print(f"\nExtracted keys into array: {keys}")
print(f"Data type: {keys.dtype}")

Array from single dictionary: {'name': 'Alice', 'age': 30}
Data type: object

Array from list of dictionaries: [{'name': 'Bob', 'age': 25} {'name': 'Charlie', 'age': 35}]
Data type: object

Extracted ages into array: [25 35]
Data type: int64

Extracted keys into array: dict_keys(['name', 'age'])
Data type: object
