<a href="https://colab.research.google.com/github/Suraram-Spandana/MDS_LABORATORY/blob/main/MDS_WEEK_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [1]:
pip install numpy


In [3]:
import numpy as np
print(np.__version__)

2.0.2


In [4]:
import time
import numpy as np

# Define a large size for comparison
size = 10**6

# --- Python List ---
print(f"Comparing Python list vs. NumPy array for {size} elements:")

# Create a Python list
start_time = time.time()
python_list = list(range(size))
end_time = time.time()
print(f"Python List creation time: {end_time - start_time:.6f} seconds")

# Perform an operation (e.g., element-wise addition)
start_time = time.time()
python_list_result = [x + 1 for x in python_list]
end_time = time.time()
print(f"Python List element-wise addition time: {end_time - start_time:.6f} seconds")

# --- NumPy Array ---

# Create a NumPy array
start_time = time.time()
numpy_array = np.arange(size)
end_time = time.time()
print(f"NumPy Array creation time: {end_time - start_time:.6f} seconds")

# Perform an operation (e.g., element-wise addition)
start_time = time.time()
numpy_array_result = numpy_array + 1
end_time = time.time()
print(f"NumPy Array element-wise addition time: {end_time - start_time:.6f} seconds")


Comparing Python list vs. NumPy array for 1000000 elements:
Python List creation time: 0.025887 seconds
Python List element-wise addition time: 0.047515 seconds
NumPy Array creation time: 0.003078 seconds
NumPy Array element-wise addition time: 0.003057 seconds


In [5]:
import sys

# --- Memory Comparison ---
print(f"\nComparing memory usage for {size} elements:")

# Memory usage of Python list
# sys.getsizeof() only reports the size of the list object itself, not the elements it contains.
# To get a more accurate total, we sum the size of the list object and each element.
python_list_memory = sys.getsizeof(python_list) + sum(sys.getsizeof(item) for item in python_list)
print(f"Python List memory usage: {python_list_memory / (1024*1024):.4f} MB")

# Memory usage of NumPy array
# .nbytes gives the total bytes consumed by the array elements.
numpy_array_memory = numpy_array.nbytes
print(f"NumPy Array memory usage: {numpy_array_memory / (1024*1024):.4f} MB")

print("\nSummary: NumPy arrays are generally more memory-efficient and significantly faster for numerical operations on large datasets compared to Python lists.")


Comparing memory usage for 1000000 elements:
Python List memory usage: 34.3323 MB
NumPy Array memory usage: 7.6294 MB

Summary: NumPy arrays are generally more memory-efficient and significantly faster for numerical operations on large datasets compared to Python lists.


list

In [8]:
my_list=[1,2,3,4,5]

In [10]:
type(my_list)


list

numpy

In [11]:
arr1=np.array(my_list)

In [12]:
print(arr1)

[1 2 3 4 5]


In [13]:
type(arr1)

numpy.ndarray

In [14]:
arr1.ndim

1

In [15]:
arr1.dtype

dtype('int64')

In [18]:
arr1.dtype.name

'int64'

In [19]:
arr1.size

5

In [20]:
arr1.shape

(5,)

array contains 5 ele


In [21]:
arr1.nbytes

40

tuple

In [22]:
my_tuple=(1,2,3,4,5)
type(my_tuple)

tuple

tuple1=(1,)----tuple
tuple2=(1)-----list

In [26]:
tuple2=(1,)

In [27]:
type(tuple2)

int

In [31]:
arr2=np.array(my_tuple)

In [ ]:
# Create a Python list of lists to represent a 2D array
python_2d_list = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Python 2D List:")
print(python_2d_list)

In [ ]:
import numpy as np

# Convert the Python list of lists to a NumPy 2D array
numpy_2d_array = np.array(python_2d_list)

print("\nNumPy 2D Array:")
print(numpy_2d_array)
print("Shape of NumPy 2D Array:", numpy_2d_array.shape)
print("Dimensions of NumPy 2D Array:", numpy_2d_array.ndim)

In [34]:
list=[[1,2],[3,4]]

In [36]:
matrix=np.array(list)
print(matrix)

[[1 2]
 [3 4]]


In [37]:
matrix.ndim

2

In [38]:
matrix.shape

(2, 2)

In [41]:
matrix.flatten()

array([1, 2, 3, 4])

In [42]:
matrix.shape


(2, 2)

In [43]:
matrix.ndim

2

In [45]:
matrix.ravel()

array([1, 2, 3, 4])

In [46]:
matrix.ndim

2

In [49]:
arr4=np.array([1,2,3,4])

In [50]:
arr5=np.array([[1,2],[3,4]])

In [51]:
print(arr5)

[[1 2]
 [3 4]]


In [54]:
arr6=np.matrix([[1,2],[3,4]])
print(arr6)

[[1 2]
 [3 4]]


In [55]:
import numpy as np

# Create a 1D array with numbers from 1 to 100 (exclusive of 101)
arr_1_to_100 = np.arange(1, 101)

print(arr_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [56]:
arr6=np.arange(1,100)
print(arr6)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [61]:
arr6=np.arange(0,100,2)
print(arr6)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [63]:
arr6=np.arange(0,100,9)
print(arr6)

[ 0  9 18 27 36 45 54 63 72 81 90 99]


In [66]:
matrix2=np.arange(0,10).reshape(2,5)
print(matrix2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
import numpy as np

# Generate numbers up to (but not including) 100, starting implicitly from 0
# Then, use slicing [::2] to get every second number, which will be the even numbers.
even_numbers = np.arange(100)[::2]

print(even_numbers)

np.zeros and np.ones

In [70]:
a=np.zeros((3,3))

In [71]:
a.dtype

dtype('float64')

In [74]:
a=np.zeros((3,3),dtype='int')
a=np.zeros((3,3))
a.dtype

dtype('float64')

In [76]:
a=np.ones((3,3),dtype='int')

a.dtype

dtype('int64')

np.full()

In [78]:
c=np.full((3,3),2)
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [80]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [81]:
f=np.linspace(0,1,5)
print(f)

[0.   0.25 0.5  0.75 1.  ]


In [84]:
g=np.random.random((3,3))
print(g)

[[0.37238272 0.37747776 0.43192531]
 [0.81680341 0.79749142 0.61389854]
 [0.70115532 0.97086223 0.35903921]]


In [86]:
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [88]:
arr1[0]=111
print(arr1)

[111   2   3   4   5   6   7   8   9]


In [90]:
arr1.max()

np.int64(111)

In [91]:
arr1.min()

np.int64(2)